import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// extension CustomFDividerStyles on Never {
///   // Modify this function's body.
///   static FDividerStyles dividerStyles({
///     required FColorScheme color,
///     required FStyle style,
///   }) => FDividerStyles(
///     horizontalStyle: FDividerStyle(
///       colors: colors.secondary,
///       padding: FDividerStyle.defaultPadding.horizontalStyle,
///       width: style.borderWidth,
///     ),
///     verticalStyle: FDividerStyle(
///       colors: colors.secondary,
///       padding: FDividerStyle.defaultPadding.verticalStyle,
///       width: style.borderWidth,
///     ),
///   );
/// }
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.color,
///  style: FThemes.neutral.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.color,
///    style: FThemes.neutral.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See:
/// * https://forui.dev/docs/guides/customizing-themes for customizing themes.
/// * https://forui.dev/docs/guides/customizing-widget-styles for customizing individual widget styles.
extension CustomFSelectMenuTileStyle on Never {
  static FSelectMenuTileStyle selectMenuTileStyle({
    required FColors colors,
    required FTypography typography,
    required FStyle style,
  }) {
    final groupStyle = _tileGroupStyle(
      colors: colors,
      style: style,
      typography: typography,
    );
    return .new(
      menuStyle: .inherit(colors: colors, style: style, typography: typography, touch: true),
      tileStyle: .inherit(colors: colors, typography: typography, style: style).copyWith(
        backgroundColor: .delta([.all(colors.background)]),
      ),
      labelTextStyle: groupStyle.labelTextStyle,
      descriptionTextStyle: groupStyle.descriptionTextStyle,
      errorTextStyle: groupStyle.errorTextStyle,
      labelPadding: groupStyle.labelPadding,
      descriptionPadding: groupStyle.descriptionPadding,
      errorPadding: groupStyle.errorPadding,
    );
  }

  static FTileGroupStyle _tileGroupStyle({
    required FColors colors,
    required FTypography typography,
    required FStyle style,
  }) => .new(
    decoration: BoxDecoration(
      border: .all(color: colors.border, width: style.borderWidth),
      borderRadius: style.borderRadius.md,
    ),
    dividerColor: .all(colors.border),
    dividerWidth: style.borderWidth,
    labelTextStyle: FVariants.from(
      typography.md.copyWith(
        color:
            style.formFieldStyle.labelTextStyle.base.color ?? colors.foreground,
        fontWeight: .w600,
      ),
      variants: {
        [.disabled]: .delta(color: colors.disable(colors.foreground)),
      },
    ),
    tileStyles: FTileStyles(FVariants.from(
      FTileStyle.inherit(colors: colors, typography: typography, style: style).copyWith(
        decoration: .delta([
          .all(const .shapeDelta(shape: RoundedSuperellipseBorder())),
        ]),
      ),
      variants: {
        [.destructive]: .delta(
          contentStyle: _itemContentStyle(
            colors: colors,
            typography: typography,
            prefix: colors.destructive,
            foreground: colors.destructive,
            mutedForeground: colors.destructive,
          ),
          rawItemContentStyle: _rawItemContentStyle(
            colors: colors,
            typography: typography,
            prefix: colors.destructive,
            color: colors.destructive,
          ),
        ),
      },
    )),
    descriptionTextStyle: style.formFieldStyle.descriptionTextStyle.apply([
      .all(
        .delta(fontSize: typography.xs.fontSize, height: typography.xs.height),
      ),
    ]),
    errorTextStyle: style.formFieldStyle.errorTextStyle.apply([
      .all(
        .delta(
          fontSize: typography.xs.fontSize,
          height: typography.xs.height,
          fontWeight: .w400,
        ),
      ),
    ]),
  );

  static FItemContentStyle _itemContentStyle({
    required FColors colors,
    required FTypography typography,
    required Color prefix,
    required Color foreground,
    required Color mutedForeground,
  }) {
    final disabledMutedForeground = colors.disable(mutedForeground);
    return FItemContentStyle(
      prefixIconStyle: FVariants.from(
        IconThemeData(color: prefix, size: 15),
        variants: {
          [.disabled]: .delta(color: colors.disable(prefix)),
        },
      ),
      titleTextStyle: FVariants.from(
        typography.sm.copyWith(color: foreground),
        variants: {
          [.disabled]: .delta(color: colors.disable(foreground)),
        },
      ),
      subtitleTextStyle: FVariants.from(
        typography.xs.copyWith(color: mutedForeground),
        variants: {
          [.disabled]: .delta(color: disabledMutedForeground),
        },
      ),
      detailsTextStyle: FVariants.from(
        typography.xs.copyWith(color: mutedForeground),
        variants: {
          [.disabled]: .delta(color: disabledMutedForeground),
        },
      ),
      suffixIconStyle: FVariants.from(
        IconThemeData(color: mutedForeground, size: 15),
        variants: {
          [.disabled]: .delta(color: disabledMutedForeground),
        },
      ),
      suffixedPadding: const EdgeInsetsDirectional.only(start: 11, top: 7.5, bottom: 7.5, end: 6),
      unsuffixedPadding: const EdgeInsetsDirectional.only(start: 11, top: 7.5, bottom: 7.5, end: 6),
      prefixIconSpacing: 10,
      titleSpacing: 3,
      middleSpacing: 4,
      suffixIconSpacing: 5,
    );
  }

  static FRawItemContentStyle _rawItemContentStyle({
    required FColors colors,
    required FTypography typography,
    required Color prefix,
    required Color color,
  }) => FRawItemContentStyle(
    prefixIconStyle: FVariants.from(
      IconThemeData(color: prefix, size: 15),
      variants: {
        [.disabled]: .delta(color: colors.disable(prefix)),
      },
    ),
    childTextStyle: FVariants(
      typography.sm.copyWith(color: color),
      variants: {
        [.disabled]: typography.sm.copyWith(color: colors.disable(color)),
      },
    ),
    padding: const EdgeInsetsDirectional.only(start: 15, top: 7.5, bottom: 7.5, end: 10),
    prefixIconSpacing: 10,
  );
}
