"""Emit the post-import coverage report SQL.

Read-only: prints SQL for a human to run with the Supabase MCP `execute_sql`.
The 228 known ward ids are inlined as a VALUES CTE from districts.json, which
is what makes "is this district value actually resolvable by the app's filter"
answerable in pure SQL rather than by eyeballing.

    .venv/bin/python verify.py > /tmp/venue_report.sql
"""

from __future__ import annotations

import json

from config import DATA


def main() -> None:
    rows = json.loads((DATA / "districts.json").read_text(encoding="utf-8"))
    values = ",\n  ".join(
        "("
        + ", ".join(
            "'" + str(r[k]).replace("'", "''") + "'" for k in ("id", "legacy", "name")
        )
        + f", {r['city_cluster']})"
        for r in rows
    )

    print(f"""-- GENERATED by tool/venue/verify.py. Read-only.
WITH known(id, legacy, name, cluster) AS (VALUES
  {values}
)

-- 1. Coverage per city. UNFILTERABLE is the headline: it counts rows no ward
--    selection can ever surface. Baseline before the overhaul was 557 (HCMC)
--    and 376 (Hanoi).
SELECT
  l.city_cluster,
  count(*)                                                        AS total,
  count(*) FILTER (WHERE btrim(l.name) <> '')                     AS named,
  count(*) FILTER (WHERE btrim(l.name)  = '')                     AS unnamed,
  count(*) FILTER (WHERE l.lat IS NOT NULL)                       AS geocoded,
  count(*) FILTER (WHERE l.district IN (SELECT id FROM known))    AS ward_id_filterable,
  count(*) FILTER (WHERE l.district IN (SELECT legacy FROM known)) AS legacy_filterable,
  count(*) FILTER (WHERE COALESCE(btrim(l.district), '') = ''
                      OR (l.district NOT IN (SELECT id FROM known)
                     AND  l.district NOT IN (SELECT legacy FROM known)
                     AND  l.district NOT IN (SELECT name FROM known)
                     AND  l.district NOT IN (SELECT 'Phường ' || name FROM known)
                     AND  l.district NOT IN (SELECT 'Xã ' || name FROM known)))
                                                                  AS unfilterable,
  count(*) FILTER (WHERE NOT l.is_verified AND l.source <> 'user_submitted')
                                                                  AS out_of_footprint
FROM public.location l
WHERE l.city_cluster IN (1, 2)
GROUP BY l.city_cluster
ORDER BY l.city_cluster;""")

    print("""
-- 2. Per-sport scorecard. Acceptance criteria are badminton (was 28 HCMC /
--    49 Hanoi) and pickleball (was 14 / 4).
SELECT l.city_cluster, s.id, s.name, count(*) AS venues
FROM public.location l
JOIN public.sport s ON s.id = ANY(l.sport_ids)
WHERE l.city_cluster IN (1, 2) AND l.is_verified
GROUP BY 1, 2, 3
ORDER BY 1, 2;

-- 3. Per-ward distribution. More useful than the totals: one ward holding
--    hundreds of venues means the polygon assembly produced a bogus giant
--    multipolygon, which the aggregate counts would happily hide.
SELECT city_cluster, district, count(*)
FROM public.location
WHERE city_cluster IN (1, 2)
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 30;

-- 4. Residual duplicates within ~60 m. Should trend to zero across runs.
SELECT a.id, b.id, a.name, b.name,
       round((2 * 6371000 * asin(sqrt(
         sin(radians(b.lat - a.lat) / 2) ^ 2
         + cos(radians(a.lat)) * cos(radians(b.lat))
         * sin(radians(b.lon - a.lon) / 2) ^ 2)))::numeric, 1) AS metres
FROM public.location a
JOIN public.location b
  ON a.id < b.id AND a.city_cluster = b.city_cluster
WHERE a.lat IS NOT NULL AND b.lat IS NOT NULL
  AND abs(a.lat - b.lat) < 0.0006 AND abs(a.lon - b.lon) < 0.0006
ORDER BY metres
LIMIT 50;

-- 5. FK integrity. Must be zero — the constraints would have blocked it, but
--    run it as the explicit assertion that the merge preserved location ids.
SELECT 'activity' AS t, count(*) FROM public.activity
 WHERE location_id IS NOT NULL
   AND location_id NOT IN (SELECT id FROM public.location)
UNION ALL
SELECT 'lobby_homeground', count(*) FROM public.lobby_homeground
 WHERE location_id NOT IN (SELECT id FROM public.location);""")


if __name__ == "__main__":
    main()
